In [2]:
import numpy as np

1. Create a 1D array of numbers from 0 to 9

In [3]:
array=np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 3×3 NumPy array of all Boolean value Trues

In [7]:
array=np.zeros((3,3))
bool_arr = array<1
bool_arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3. Extract all odd numbers from array of 1 10

In [16]:
array=np.arange(11)
odd_arr=array[array%2!=0]
odd_arr


array([1, 3, 5, 7, 9])

In [17]:
even_arr=array[array%2==0]
even_arr

array([ 0,  2,  4,  6,  8, 10])

4. Replace all odd numbers in an array of 1 10 with the value 1

In [37]:
array[array%2!=0]=-1
odd_replaced=array
print(odd_replaced)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


5. Convert a 1D array to a 2D array with 2 rows

In [36]:
array=np.arange(10)
array.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

6. Create two arrays a and b, stack these two arrays vertically use the np.dot and
np.sum to calculate totals

In [44]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print(np.dot(a,b))
c = np.vstack((a,b))
print(c)
e = np.sum(c, axis = 0)
print("np.sum(c, axis=0)=",e)
f = np.sum(c, axis = 1)
print("np.sum(c, axis=1)=",f)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
np.sum(c, axis=0)= [51 57 63]
np.sum(c, axis=1)= [ 6 15 24 33 42 51]


Extension
1. Create the following pattern without hardcoding. Use only NumPy functions

In [74]:
list=[1,2,3]
a=np.array(list)
b=np.transpose(np.vstack((a,a,a))).flatten()
c=np.hstack((a,a,a))
d=np.append(b,c)
print(d)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [92]:
# Or this is an easier way
a=np.array([1,2,3])
np.concatenate((np.repeat(a,3, axis=0),np.hstack((a,a,a))))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

2. In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) remove all repeating items present in array b

In [84]:
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8,9])
commonelements, a_ind, b_ind = np.intersect1d(a,b,return_indices=True)
newb=np.delete(b,b_ind)
newb

array([6, 7, 8, 9])

3. Get all items between 3 and 7 from a and b and sum them together

In [91]:
np.sum(np.where((a>3) & (a<7)))+np.sum(np.where((b>3) & (b<7)))

10